### ISSUE TITLE
bitcoin qt not able to recognize my local test net

### ISSUE THREAD

**Issue by smatthewenglish** [c0achmcguirk/docker-bitcoin-abe#2]
I've created a local test net here: 

https://github.com/s-matthew-english/local_testnet

I tried to run bitcoin-qt to import those few transactions I created- with this command: 

/path/to/bitcoin-qt \ -regtest -dnsseed=0 -connect=localhost:49020 \ -datadir=./localnet/

but I saw it was still trying to download the real bitcoin blockchain or the test net- since it said 7 years behind. 

so I tried to replace all with this command: 

/usr/bin/bitcoin-qt -conf=/home/lab/bitcoin-testnet-box/1/bitcoin.conf -datadir=/home/lab/localnet/ -loadblock=/home/lab/bitcoin-testnet-box/1/regtest/blocks/blk00000.dat -wallet=/home/lab/bitcoin-testnet-box/1/regtest/wallet.dat

but then bitcoin-qt gave the error message "unable to connect to http" and it wouldn't start. 

how can I use some wallet service to see the local testnet data I've created- such that I can eventually export it to abe?

**Comment by c0achmcguirk** [comment]
I'm noticing a few things:
- Make sure you do this _AFTER_ you start bitcoin-dev-box.
- You shouldn't type the `\` characters on the command line. I do that in the README to show where the line is wrapping. Sorry for the confusion.
- Unless you're running on Linux, the server you're connecting to is **NOT** `localhost` but your `dockerhost`. I think you're doing this on linux so you're probably fine.
